server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/

spring:
  application:
      name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hawkingdu/springcloudlearning
          search-paths: cloud-config
          username:
          password:
